# Trivy Configuration File
# This file configures Trivy to properly scan Helm charts by providing values
# so templates can be rendered and validated against actual registry values.

misconfiguration:
  helm:
    # Provide Helm values file so Trivy can render templates and verify
    # that container images use trusted registries (ghcr.io by default)
    values:
      - charts/app/values.yaml
