apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Product name
    required: true
  - name: COMPONENT
    description: Component name
    value: database
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: IMAGE_TAG
    description: Image tag to use
    required: true
  - name: REGISTRY
    description: Container registry to import from
    value: image-registry.openshift-image-registry.svc:5000
  - name: ORG_NAME
    description: Organization name
    value: openshift
  - name: DB_PVC_SIZE
    description: Volume space available for data
    value: 256Mi
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: ${DB_PVC_SIZE}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      replicas: 1
      selector:
        matchLabels:
          deployment: ${NAME}-${ZONE}-${COMPONENT}
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: ${NAME}-${ZONE}
            deployment: ${NAME}-${ZONE}-${COMPONENT}
        spec:
          containers:
            - name: postgresql
              image: ${REGISTRY}/${ORG_NAME}/postgresql-15:${IMAGE_TAG}
              imagePullPolicy: Always
              ports:
                - name: postgresql
                  containerPort: 5432
              volumeMounts:
                - name: ${NAME}-${ZONE}-data
                  mountPath: /var/lib/postgresql/data
              resources:
                requests:
                  cpu: 10m
                  memory: 50Mi
          volumes:
            - name: ${NAME}-${ZONE}-data
              persistentVolumeClaim:
                claimName: ${NAME}-${ZONE}-${COMPONENT}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      ports:
        - name: postgresql
          port: 5432
          targetPort: 5432
      selector:
        deployment: ${NAME}-${ZONE}-${COMPONENT}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
    spec:
      podSelector: {}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
    spec:
      podSelector: {}
      ingress:
        - from:
            - podSelector: {}
      policyTypes:
        - Ingress