apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Product name
    value: quickstart-openshift
  - name: PG_DATABASE
    description: Postgres database name
    value: app
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: DB_PASSWORD
    description: Password for the PostgreSQL connection user.
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-database
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      database-name: ${PG_DATABASE}
      database-password: ${DB_PASSWORD}
      database-user: ${NAME}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: ${NAME}-${ZONE}-frontend-ingress
      labels:
        app: ${NAME}-${ZONE}
    spec:
      podSelector:
        matchLabels:
          deployment: ${NAME}-${ZONE}-frontend
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: ${NAME}-${ZONE}-backend-ingress
      labels:
        app: ${NAME}-${ZONE}
    spec:
      podSelector:
        matchLabels:
          deployment: ${NAME}-${ZONE}-backend
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  app: ${NAME}-${ZONE}
                  deployment: ${NAME}-${ZONE}-frontend
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: ${NAME}-${ZONE}-database-ingress
      labels:
        app: ${NAME}-${ZONE}
    spec:
      podSelector:
        matchLabels:
          deployment: ${NAME}-${ZONE}-database
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  app: ${NAME}-${ZONE}
                  deployment: ${NAME}-${ZONE}-backend
      policyTypes:
        - Ingress
