name: .Deploys

on:
  workflow_call:
    inputs:
      environment:
        description: GitHub/OpenShift environment
        default: ""
        type: string
      target:
        description: Deployment target; usually PR number, test or prod
        default: ${{ github.event.number }}
        type: string
      tag:
        description: Container tag
        default: ${{ github.event.number }}
        type: string
      triggers:
        description: Triggers for deployment
        default: ""
        type: string

    secrets:
      oc_namespace:
        description: OpenShift namespace
        required: true
      oc_token:
        description: OpenShift token
        required: true

    outputs:
      triggered:
        description: Has deployment been triggered?
        value: ${{ jobs.deploy.outputs.triggered }}

permissions: {}

jobs:
  init:
    name: Deploy (init)
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-24.04
    steps:
      - name: OpenShift Init
        id: deploy
        uses: bcgov/action-deployer-openshift@565e315dfddb8aee08fcfd885a27407dde9a2775 # v4.0.1
        with:
          oc_namespace: ${{ secrets.oc_namespace }}
          oc_token: ${{ secrets.oc_token }}
          file: common/openshift.init.yml
          overwrite: true
          parameters: -p ZONE=${{ inputs.target }}
          triggers: ${{ inputs.triggers }}

  deploy:
    name: Deploy (${{ matrix.name }})
    environment: ${{ inputs.environment }}
    needs: [init]
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    outputs:
      triggered: ${{ steps.deploy.outputs.triggered }}
    strategy:
      matrix:
        name: [database, backend, frontend]
        include:
          - name: database
            file: common/openshift.database.yml
            overwrite: false
          - name: backend
            file: backend/openshift.deploy.yml
            overwrite: true
            verification_path: /actuator/health
          - name: frontend
            file: frontend/openshift.deploy.yml
            overwrite: true
    steps:
      - uses: bcgov/action-deployer-openshift@565e315dfddb8aee08fcfd885a27407dde9a2775 # v4.0.1
        id: deploy
        with:
          file: ${{ matrix.file }}
          oc_namespace: ${{ secrets.oc_namespace }}
          oc_token: ${{ secrets.oc_token }}
          overwrite: ${{ matrix.overwrite }}
          parameters: -p ZONE=${{ inputs.target }} -p TAG=${{ inputs.tag }}
          timeout: 15m
          triggers: ${{ inputs.triggers }}
          verification_path: ${{ matrix.verification_path }}