name: Analysis

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 11 * * 0" # 3 AM PST = 12 PM UDT, runs sundays
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/.unit-tests.yml
    secrets:
      SONAR_TOKEN_BACKEND: ${{ secrets.SONAR_TOKEN_BACKEND }}
      SONAR_TOKEN_FRONTEND: ${{ secrets.SONAR_TOKEN_FRONTEND }}

  results:
    name: Analysis Results
    needs: [unit-tests]
    if: always()
    runs-on: ubuntu-slim
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'canceled')
        run: exit 1
      - run: echo "Success!"
