name: PR Validate

on:
  pull_request:
    types: [edited, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  validate:
    name: Validate PR
    if: (! github.event.pull_request.draft)
    runs-on: ubuntu-24.04
    steps:
      - uses: bcgov/actions/pr-validate@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  results:
    name: Validate Results
    if: always()
    needs: [validate]
    runs-on: ubuntu-slim
    steps:
      - run: echo "Success!"
