{{- if and .Values.global.secrets .Values.global.secrets.enabled}}
{{- $databaseUser := .Values.global.secrets.databaseUser| default "quickstart"  }}
{{- $databasePassword := .Values.global.secrets.databasePassword }}
{{- $databaseName := .Values.global.secrets.databaseName| default "quickstart" }}
{{- $host := printf "%s-%s:5432" .Release.Name .Values.global.databaseAlias }}
{{- $databaseURL := printf "postgresql://%s:%s@%s/%s" $databaseUser $databasePassword $host $databaseName }}
{{- $databaseJDBCURL := printf "jdbc:postgresql://%s:%s@%s/%s" $databaseUser $databasePassword $host $databaseName }}
{{- $databaseJDBCURLNoCreds := printf "jdbc:postgresql://%s/%s" $host $databaseName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "selectorLabels" . | nindent 4 }}
data:
  databasePassword: {{ $databasePassword | b64enc | quote }}
  postgres-password: {{ $databasePassword | b64enc | quote }}
  password: {{ $databasePassword | b64enc | quote }}
  databaseUser: {{  $databaseUser | b64enc | quote }}
  databaseName: {{  $databaseName | b64enc | quote }}
  databaseURL: {{ $databaseURL | b64enc | quote }}
  databaseJDBCURL: {{ $databaseJDBCURL | b64enc | quote }}
  databaseJDBCURLNoCreds: {{ $databaseJDBCURLNoCreds | b64enc | quote }}
{{- end }}
